package health

import (
	"context"
	"fmt"
	"os"
	"strings"

	"github.com/iodesystems/ubuntu-router/internal/network"
	"github.com/iodesystems/ubuntu-router/internal/system"
)

// RouterConfig contains the configuration values needed for health checks
type RouterConfig struct {
	LANBridge    string
	LANAddresses []string
	WANInterface string
	WANMode      string // dhcp, static, pppoe, wifi
	DHCPStart    string
	DHCPEnd      string
	// WireGuard interfaces to check
	WireGuardInterfaces []WireGuardInterfaceConfig
	// WiFi interfaces configured as access points (LAN, not WAN)
	WiFiAPInterfaces []string
}

// WireGuardInterfaceConfig contains WireGuard interface config for health checks
type WireGuardInterfaceConfig struct {
	Name       string // e.g., "wg0", "wg1"
	ConfigPath string // e.g., "/etc/wireguard/wg0.conf"
	Enabled    bool
}

// RegisterAllChecks registers all standard health checks
func RegisterAllChecks(runner *Runner, cmdRunner system.CommandRunner, fs system.FileSystem) {
	RegisterAllChecksWithConfig(runner, cmdRunner, fs, nil)
}

// RegisterAllChecksWithConfig registers all health checks with router config for enhanced checks
func RegisterAllChecksWithConfig(runner *Runner, cmdRunner system.CommandRunner, fs system.FileSystem, cfg *RouterConfig) {
	// Use defaults if no config provided
	if cfg == nil {
		cfg = &RouterConfig{
			LANBridge:    "br0",
			LANAddresses: []string{"192.168.1.1/24"},
			WANInterface: "",
			DHCPStart:    "192.168.1.100",
			DHCPEnd:      "192.168.1.200",
		}
	}

	// Root check - many things depend on this
	runner.Register(NewRootCheck(cmdRunner, fs))

	// Package manager check
	runner.Register(NewAptCheck(cmdRunner, fs))

	// Service checks - include executable, config validation, and service status
	// Dnsmasq: DNS and DHCP server
	// Minimal config uses bind-dynamic for systemd-resolved compatibility
	dnsmasqMinimalConfig := `# Ubuntu Router DNS configuration
# Minimal config for systemd-resolved compatibility
# Full config will be written when router is configured

# Required for systemd-resolved compatibility - allows coexistence on port 53
bind-dynamic
except-interface=lo

# Use upstream DNS until configured
server=8.8.8.8
server=8.8.4.4
`
	runner.Register(NewServiceCheck("dnsmasq", "Dnsmasq", "dnsmasq",
		"DNS and DHCP server (executable, config, service)",
		[]string{"apt"}, cmdRunner, fs,
		WithConfigPath("/etc/dnsmasq.d/ubuntu-router-dns.conf"),
		WithTestCommand("dnsmasq", "--test", "-C"),
		WithMinimalConfig(dnsmasqMinimalConfig),
	))

	// HAProxy: Load balancer and reverse proxy for Services
	// Minimal config for HAProxy to start (actual config generated by services sync)
	haproxyMinimalConfig := `# Ubuntu Router HAProxy configuration
# Minimal config - run services sync to generate full config

global
    log /dev/log local0
    log /dev/log local1 notice
    chroot /var/lib/haproxy
    stats socket /run/haproxy/admin.sock mode 660 level admin expose-fd listeners
    stats timeout 30s
    user haproxy
    group haproxy
    daemon

defaults
    log global
    mode http
    option httplog
    option dontlognull
    timeout connect 5000
    timeout client  50000
    timeout server  50000
    errorfile 400 /etc/haproxy/errors/400.http
    errorfile 403 /etc/haproxy/errors/403.http
    errorfile 408 /etc/haproxy/errors/408.http
    errorfile 500 /etc/haproxy/errors/500.http
    errorfile 502 /etc/haproxy/errors/502.http
    errorfile 503 /etc/haproxy/errors/503.http
    errorfile 504 /etc/haproxy/errors/504.http

# No services configured yet - use Services page to add services
`
	runner.Register(NewServiceCheck("haproxy", "HAProxy", "haproxy",
		"Load balancer/reverse proxy (executable, config, service)",
		[]string{"apt"}, cmdRunner, fs,
		WithConfigPath("/etc/haproxy/haproxy.cfg"),
		WithTestCommand("haproxy", "-c", "-f"),
		WithMinimalConfig(haproxyMinimalConfig),
	))

	// Hostapd: WiFi access point daemon
	// Note: hostapd uses per-interface services (hostapd-wlan0, etc.), not the default
	// masked hostapd service. We only check for the executable here.
	runner.Register(NewExecutableCheck("hostapd", "Hostapd", "WiFi access point daemon",
		[]string{"apt"}, cmdRunner, fs))

	// Simple executable checks for tools that don't have managed services
	runner.Register(NewExecutableCheck("wg", "WireGuard Tools", "VPN tools (wg command)",
		[]string{"apt"}, cmdRunner, fs))
	runner.Register(NewExecutableCheck("iptables", "iptables", "Firewall management",
		[]string{"apt"}, cmdRunner, fs))
	runner.Register(NewExecutableCheck("ip", "iproute2", "Network interface management",
		[]string{"apt"}, cmdRunner, fs))
	runner.Register(NewExecutableCheck("iw", "Wireless Tools", "WiFi interface management",
		[]string{"apt"}, cmdRunner, fs))

	// Kernel module checks - depend on wireguard tools being available
	runner.Register(NewKernelModuleCheck("wireguard-module", "WireGuard Kernel Module",
		"wireguard", []string{"wg"}, cmdRunner, fs))

	// Network checks - depend on ip command
	runner.Register(NewNetworkCheck(cmdRunner, fs))

	// IP forwarding check
	runner.Register(NewIPForwardingCheck(cmdRunner, fs))

	// WiFi AP capability check - depend on iw
	runner.Register(NewWiFiInterfaceCheck(cmdRunner, fs))

	// Router-specific checks

	// LAN Gateway check - verify bridge has gateway IP
	expectedIP := ""
	if len(cfg.LANAddresses) > 0 {
		expectedIP = cfg.LANAddresses[0]
	}
	runner.Register(NewLANGatewayCheck(cfg.LANBridge, expectedIP, cfg.WANInterface, cmdRunner, fs))

	// NAT/Masquerade check - verify NAT is configured for routing
	runner.Register(NewNATCheck(cfg.WANInterface, cfg.WANMode, cfg.WiFiAPInterfaces, cmdRunner, fs))

	// DHCP Range check - verify DHCP is configured
	runner.Register(NewDHCPRangeCheck(cfg.DHCPStart, cfg.DHCPEnd, "", cfg.WANInterface, cfg.LANBridge, cmdRunner, fs))

	// systemd-resolved check - verify no DNS port conflicts
	runner.Register(NewSystemdResolvedCheck(cmdRunner, fs))

	// WireGuard interface checks - register checks for configured interfaces
	for _, wgIface := range cfg.WireGuardInterfaces {
		runner.Register(NewWireGuardInterfaceCheck(wgIface.Name, wgIface.ConfigPath, wgIface.Enabled, cmdRunner, fs))
	}
}

// RootCheck verifies we have root privileges
type RootCheck struct {
	BaseCheck
}

func NewRootCheck(runner system.CommandRunner, fs system.FileSystem) *RootCheck {
	return &RootCheck{
		BaseCheck: NewBaseCheck("root", "Root Privileges", "Check for root/sudo access", nil, runner, fs),
	}
}

func (c *RootCheck) Run(ctx context.Context) *Status {
	status := &Status{
		CheckID:     c.ID(),
		Name:        c.Name(),
		Description: c.Description(),
	}

	if os.Geteuid() == 0 {
		status.State = StateOK
		status.Message = "Running as root"
	} else {
		status.State = StateWarning
		status.Message = "Not running as root - some operations may fail"
		status.Issues = append(status.Issues, Issue{
			Severity: SeverityWarning,
			Message:  "Application is not running with root privileges",
			Details:  "Run with sudo or as root for full functionality",
		})
	}

	return status
}

// AptCheck verifies apt package manager is available
type AptCheck struct {
	BaseCheck
}

func NewAptCheck(runner system.CommandRunner, fs system.FileSystem) *AptCheck {
	return &AptCheck{
		BaseCheck: NewBaseCheck("apt", "APT Package Manager", "Check if apt is available", nil, runner, fs),
	}
}

func (c *AptCheck) Run(ctx context.Context) *Status {
	status := &Status{
		CheckID:     c.ID(),
		Name:        c.Name(),
		Description: c.Description(),
	}

	// Check if apt-get exists
	if _, err := c.runner.Run(ctx, "which", "apt-get"); err != nil {
		status.State = StateError
		status.Message = "apt-get not found"
		status.Issues = append(status.Issues, Issue{
			Severity: SeverityCritical,
			Message:  "apt-get command not found",
			Details:  "This system does not appear to be Debian/Ubuntu-based",
		})
		return status
	}

	status.State = StateOK
	status.Message = "APT package manager available"
	return status
}

// ExecutableCheck verifies an executable is installed
type ExecutableCheck struct {
	BaseCheck
	execName    string
	packageName string
}

func NewExecutableCheck(id, name, description string, deps []string, runner system.CommandRunner, fs system.FileSystem) *ExecutableCheck {
	return &ExecutableCheck{
		BaseCheck: NewBaseCheck(id, name, description, deps, runner, fs),
	}
}

func (c *ExecutableCheck) Run(ctx context.Context) *Status {
	status := &Status{
		CheckID:     c.ID(),
		Name:        c.Name(),
		Description: c.Description(),
	}

	execName := c.id
	packageName := c.getPackageName()

	// Try to find the executable
	out, err := c.runner.Run(ctx, "which", execName)
	if err != nil {
		status.State = StateError
		status.Message = fmt.Sprintf("%s not found", execName)

		fixerID := fmt.Sprintf("install-%s", c.id)
		issue := Issue{
			Severity: SeverityCritical,
			Message:  fmt.Sprintf("Executable '%s' not found in PATH", execName),
			Details:  fmt.Sprintf("Install with: sudo apt-get install %s", packageName),
			FixerID:  fixerID,
			FixerDesc: fmt.Sprintf("Install %s package", packageName),
			Fixer: &Fixer{
				Description:  fmt.Sprintf("Install %s via apt", packageName),
				RequiresRoot: true,
				Fix: func(ctx context.Context) error {
					_, err := c.runner.Run(ctx, "apt-get", "install", "-y", packageName)
					return err
				},
			},
		}
		status.Issues = append(status.Issues, issue)
		return status
	}

	path := strings.TrimSpace(string(out))
	status.State = StateOK
	status.Message = fmt.Sprintf("Found at %s", path)
	return status
}

func (c *ExecutableCheck) getPackageName() string {
	// Map check IDs (executable names) to package names
	packageMap := map[string]string{
		"hostapd":  "hostapd",
		"dnsmasq":  "dnsmasq",
		"wg":       "wireguard-tools",
		"iptables": "iptables",
		"ip":       "iproute2",
		"iw":       "iw",
		"ifconfig": "net-tools",
		"haproxy":  "haproxy",
	}
	if pkg, ok := packageMap[c.id]; ok {
		return pkg
	}
	return c.id
}

// KernelModuleCheck verifies a kernel module is available/loaded
type KernelModuleCheck struct {
	BaseCheck
	moduleName string
}

func NewKernelModuleCheck(id, name, moduleName string, deps []string, runner system.CommandRunner, fs system.FileSystem) *KernelModuleCheck {
	return &KernelModuleCheck{
		BaseCheck:  NewBaseCheck(id, name, fmt.Sprintf("Check %s kernel module", moduleName), deps, runner, fs),
		moduleName: moduleName,
	}
}

func (c *KernelModuleCheck) Run(ctx context.Context) *Status {
	status := &Status{
		CheckID:     c.ID(),
		Name:        c.Name(),
		Description: c.Description(),
	}

	// Check if module is loaded
	out, err := c.runner.Run(ctx, "lsmod")
	if err != nil {
		status.State = StateWarning
		status.Message = "Could not check loaded modules"
		return status
	}

	if strings.Contains(string(out), c.moduleName) {
		status.State = StateOK
		status.Message = fmt.Sprintf("Module %s is loaded", c.moduleName)
		return status
	}

	// Module not loaded - check if it's available
	_, err = c.runner.Run(ctx, "modinfo", c.moduleName)
	if err != nil {
		status.State = StateError
		status.Message = fmt.Sprintf("Module %s not available", c.moduleName)
		status.Issues = append(status.Issues, Issue{
			Severity: SeverityCritical,
			Message:  fmt.Sprintf("Kernel module '%s' is not available", c.moduleName),
			Details:  "The module may need to be installed or the kernel upgraded",
		})
		return status
	}

	// Module available but not loaded
	fixerID := fmt.Sprintf("load-%s", c.moduleName)
	status.State = StateWarning
	status.Message = fmt.Sprintf("Module %s available but not loaded", c.moduleName)
	moduleName := c.moduleName
	status.Issues = append(status.Issues, Issue{
		Severity:  SeverityWarning,
		Message:   fmt.Sprintf("Kernel module '%s' is not loaded", c.moduleName),
		Details:   fmt.Sprintf("Load with: sudo modprobe %s", c.moduleName),
		FixerID:   fixerID,
		FixerDesc: fmt.Sprintf("Load %s module", c.moduleName),
		Fixer: &Fixer{
			Description:  fmt.Sprintf("Load kernel module %s (persistent)", c.moduleName),
			RequiresRoot: true,
			Fix: func(ctx context.Context) error {
				// Write persistent config for auto-loading on boot
				c.fs.WriteFile(fmt.Sprintf("/etc/modules-load.d/%s.conf", moduleName), []byte(moduleName+"\n"), 0644)
				// Load immediately
				_, err := c.runner.Run(ctx, "modprobe", moduleName)
				return err
			},
		},
	})

	return status
}

// NetworkCheck verifies network interfaces are available
type NetworkCheck struct {
	BaseCheck
}

func NewNetworkCheck(runner system.CommandRunner, fs system.FileSystem) *NetworkCheck {
	return &NetworkCheck{
		BaseCheck: NewBaseCheck("network", "Network Interfaces", "Check network interface availability", []string{"ip"}, runner, fs),
	}
}

func (c *NetworkCheck) Run(ctx context.Context) *Status {
	status := &Status{
		CheckID:     c.ID(),
		Name:        c.Name(),
		Description: c.Description(),
	}

	out, err := c.runner.Run(ctx, "ip", "link", "show")
	if err != nil {
		status.State = StateError
		status.Message = "Failed to list network interfaces"
		return status
	}

	lines := strings.Split(string(out), "\n")
	var interfaces []string
	for _, line := range lines {
		if strings.Contains(line, ": ") && !strings.HasPrefix(strings.TrimSpace(line), " ") {
			parts := strings.Split(line, ": ")
			if len(parts) >= 2 {
				iface := parts[1]
				// Skip loopback
				if iface != "lo" {
					interfaces = append(interfaces, iface)
				}
			}
		}
	}

	if len(interfaces) == 0 {
		status.State = StateError
		status.Message = "No network interfaces found"
		status.Issues = append(status.Issues, Issue{
			Severity: SeverityCritical,
			Message:  "No network interfaces detected",
			Details:  "At least one network interface is required for router functionality",
		})
		return status
	}

	status.State = StateOK
	status.Message = fmt.Sprintf("Found %d interface(s): %s", len(interfaces), strings.Join(interfaces, ", "))

	// Check for WiFi interfaces
	wifiOut, _ := c.runner.Run(ctx, "iw", "dev")
	if !strings.Contains(string(wifiOut), "Interface") {
		status.Issues = append(status.Issues, Issue{
			Severity: SeverityInfo,
			Message:  "No WiFi interfaces detected",
			Details:  "WiFi access point functionality requires a compatible wireless adapter",
		})
	}

	return status
}

// IPForwardingCheck verifies IP forwarding is enabled
type IPForwardingCheck struct {
	BaseCheck
}

func NewIPForwardingCheck(runner system.CommandRunner, fs system.FileSystem) *IPForwardingCheck {
	return &IPForwardingCheck{
		BaseCheck: NewBaseCheck("ip-forwarding", "IP Forwarding", "Check if IP forwarding is enabled", []string{"root"}, runner, fs),
	}
}

func (c *IPForwardingCheck) Run(ctx context.Context) *Status {
	status := &Status{
		CheckID:     c.ID(),
		Name:        c.Name(),
		Description: c.Description(),
	}

	// Check IPv4 forwarding
	ipv4Data, err := c.fs.ReadFile("/proc/sys/net/ipv4/ip_forward")
	ipv4Enabled := err == nil && strings.TrimSpace(string(ipv4Data)) == "1"

	// Check IPv6 forwarding
	ipv6Data, err := c.fs.ReadFile("/proc/sys/net/ipv6/conf/all/forwarding")
	ipv6Enabled := err == nil && strings.TrimSpace(string(ipv6Data)) == "1"

	if ipv4Enabled && ipv6Enabled {
		status.State = StateOK
		status.Message = "IPv4 and IPv6 forwarding enabled"
		return status
	}

	if ipv4Enabled {
		status.State = StateWarning
		status.Message = "Only IPv4 forwarding enabled"
		status.Issues = append(status.Issues, Issue{
			Severity:  SeverityWarning,
			Message:   "IPv6 forwarding is not enabled",
			Details:   "Enable with: sysctl -w net.ipv6.conf.all.forwarding=1",
			FixerID:   "enable-ipv6-forward",
			FixerDesc: "Enable IPv6 forwarding",
			Fixer: &Fixer{
				Description:  "Enable IPv6 forwarding via sysctl (persistent)",
				RequiresRoot: true,
				Fix: func(ctx context.Context) error {
					// Write persistent config (includes both IPv4 and IPv6)
					sysctlConfig := "# Ubuntu Router - IP forwarding\nnet.ipv4.ip_forward=1\nnet.ipv6.conf.all.forwarding=1\n"
					c.fs.WriteFile("/etc/sysctl.d/99-ubuntu-router.conf", []byte(sysctlConfig), 0644)
					// Apply immediately
					_, err := c.runner.Run(ctx, "sysctl", "-w", "net.ipv6.conf.all.forwarding=1")
					return err
				},
			},
		})
		return status
	}

	status.State = StateError
	status.Message = "IP forwarding not enabled"

	if !ipv4Enabled {
		status.Issues = append(status.Issues, Issue{
			Severity:  SeverityCritical,
			Message:   "IPv4 forwarding is not enabled",
			Details:   "Required for routing. Enable with: sysctl -w net.ipv4.ip_forward=1",
			FixerID:   "enable-ipv4-forward",
			FixerDesc: "Enable IPv4 forwarding",
			Fixer: &Fixer{
				Description:  "Enable IPv4 forwarding via sysctl (persistent)",
				RequiresRoot: true,
				Fix: func(ctx context.Context) error {
					// Write persistent config
					sysctlConfig := "# Ubuntu Router - IP forwarding\nnet.ipv4.ip_forward=1\nnet.ipv6.conf.all.forwarding=1\n"
					c.fs.WriteFile("/etc/sysctl.d/99-ubuntu-router.conf", []byte(sysctlConfig), 0644)
					// Apply immediately
					_, err := c.runner.Run(ctx, "sysctl", "-w", "net.ipv4.ip_forward=1")
					return err
				},
			},
		})
	}

	return status
}

// ServiceCheck checks a systemd service for: executable installed, config valid, and service running
type ServiceCheck struct {
	BaseCheck
	serviceName    string
	configPath     string
	testCmd        []string // Command to test config (e.g., ["dnsmasq", "--test", "-C"])
	minimalConfig  string   // Minimal config to write before starting service (for systemd-resolved compatibility)
}

// ServiceCheckOption configures a ServiceCheck
type ServiceCheckOption func(*ServiceCheck)

// WithConfigPath sets the config path to check
func WithConfigPath(path string) ServiceCheckOption {
	return func(c *ServiceCheck) {
		c.configPath = path
	}
}

// WithTestCommand sets the command to test config validity
func WithTestCommand(cmd ...string) ServiceCheckOption {
	return func(c *ServiceCheck) {
		c.testCmd = cmd
	}
}

// WithMinimalConfig sets a minimal config to write before starting service
// This is needed for services like dnsmasq that need bind-dynamic before they can start
func WithMinimalConfig(config string) ServiceCheckOption {
	return func(c *ServiceCheck) {
		c.minimalConfig = config
	}
}

// NewServiceCheck creates a new service check
func NewServiceCheck(id, name, serviceName, description string, deps []string, runner system.CommandRunner, fs system.FileSystem, opts ...ServiceCheckOption) *ServiceCheck {
	c := &ServiceCheck{
		BaseCheck:   NewBaseCheck(id, name, description, deps, runner, fs),
		serviceName: serviceName,
	}
	for _, opt := range opts {
		opt(c)
	}
	return c
}

func (c *ServiceCheck) Run(ctx context.Context) *Status {
	status := &Status{
		CheckID:     c.ID(),
		Name:        c.Name(),
		Description: c.Description(),
	}

	execName := c.id
	packageName := c.getPackageName()
	services := system.NewServiceManager(c.runner)

	// Sub-check 1: Executable installed
	execStatus := &Status{
		CheckID:     c.id + "-executable",
		Name:        "Executable",
		Description: fmt.Sprintf("Check if %s is installed", execName),
	}

	out, err := c.runner.Run(ctx, "which", execName)
	if err != nil {
		execStatus.State = StateError
		execStatus.Message = fmt.Sprintf("%s not found", execName)
		fixerID := fmt.Sprintf("install-%s", c.id)
		execStatus.Issues = append(execStatus.Issues, Issue{
			Severity:  SeverityCritical,
			Message:   fmt.Sprintf("Executable '%s' not found in PATH", execName),
			Details:   fmt.Sprintf("Install with: sudo apt-get install %s", packageName),
			FixerID:   fixerID,
			FixerDesc: fmt.Sprintf("Install %s package", packageName),
			Fixer: &Fixer{
				Description:  fmt.Sprintf("Install %s via apt", packageName),
				RequiresRoot: true,
				Fix: func(ctx context.Context) error {
					_, err := c.runner.Run(ctx, "apt-get", "install", "-y", packageName)
					return err
				},
			},
		})
		status.SubChecks = append(status.SubChecks, execStatus)
		status.State = StateError
		status.Message = fmt.Sprintf("%s not installed", execName)
		status.Issues = execStatus.Issues
		return status
	}

	path := strings.TrimSpace(string(out))
	execStatus.State = StateOK
	execStatus.Message = fmt.Sprintf("Found at %s", path)
	status.SubChecks = append(status.SubChecks, execStatus)

	// Sub-check 2: Config file (if configPath is set)
	if c.configPath != "" {
		configStatus := &Status{
			CheckID:     c.id + "-config",
			Name:        "Configuration",
			Description: fmt.Sprintf("Check if %s config is valid", c.serviceName),
		}

		_, err := c.fs.Stat(c.configPath)
		if err != nil {
			// Config not found is OK - it will be generated when service is configured
			configStatus.State = StateOK
			configStatus.Message = "No custom config (using defaults)"
		} else if len(c.testCmd) > 0 {
			// Test config validity
			testArgs := append(c.testCmd[1:], c.configPath)
			testOut, err := c.runner.Run(ctx, c.testCmd[0], testArgs...)
			if err != nil {
				configStatus.State = StateError
				configStatus.Message = "Config validation failed"
				configStatus.Issues = append(configStatus.Issues, Issue{
					Severity: SeverityCritical,
					Message:  "Configuration file is invalid",
					Details:  fmt.Sprintf("Test output: %s", strings.TrimSpace(string(testOut))),
				})
			} else {
				configStatus.State = StateOK
				configStatus.Message = fmt.Sprintf("Config at %s is valid", c.configPath)
			}
		} else {
			configStatus.State = StateOK
			configStatus.Message = fmt.Sprintf("Config exists at %s", c.configPath)
		}
		status.SubChecks = append(status.SubChecks, configStatus)
	}

	// Sub-check 3: Service status
	serviceStatus := &Status{
		CheckID:     c.id + "-service",
		Name:        "Service Status",
		Description: fmt.Sprintf("Check if %s service is running", c.serviceName),
	}

	// First check if service is masked
	statusOut, _ := c.runner.Run(ctx, "systemctl", "is-enabled", c.serviceName)
	isMasked := strings.TrimSpace(string(statusOut)) == "masked"

	if isMasked {
		serviceStatus.State = StateWarning
		serviceStatus.Message = fmt.Sprintf("%s service is masked", c.serviceName)
		fixerID := fmt.Sprintf("unmask-%s", c.serviceName)
		serviceStatus.Issues = append(serviceStatus.Issues, Issue{
			Severity:  SeverityWarning,
			Message:   fmt.Sprintf("Service %s is masked (disabled by systemd)", c.serviceName),
			Details:   fmt.Sprintf("Unmask with: sudo systemctl unmask %s", c.serviceName),
			FixerID:   fixerID,
			FixerDesc: fmt.Sprintf("Unmask %s service", c.serviceName),
			Fixer: &Fixer{
				Description:  fmt.Sprintf("Unmask %s service", c.serviceName),
				RequiresRoot: true,
				Fix: func(ctx context.Context) error {
					_, err := c.runner.Run(ctx, "systemctl", "unmask", c.serviceName)
					return err
				},
			},
		})
	} else if services.IsActive(ctx, c.serviceName) {
		// Service is running - check if it's enabled on boot
		isEnabled := services.IsEnabled(ctx, c.serviceName)
		if isEnabled {
			serviceStatus.State = StateOK
			serviceStatus.Message = fmt.Sprintf("%s service is running and enabled", c.serviceName)
		} else {
			serviceStatus.State = StateWarning
			serviceStatus.Message = fmt.Sprintf("%s service is running but not enabled on boot", c.serviceName)
			svcName := c.serviceName
			serviceStatus.Issues = append(serviceStatus.Issues, Issue{
				Severity:  SeverityWarning,
				Message:   fmt.Sprintf("Service %s is not enabled to start on boot", c.serviceName),
				Details:   fmt.Sprintf("Enable with: sudo systemctl enable %s", c.serviceName),
				FixerID:   fmt.Sprintf("enable-%s", c.serviceName),
				FixerDesc: fmt.Sprintf("Enable %s on boot", c.serviceName),
				Fixer: &Fixer{
					Description:  fmt.Sprintf("Enable %s service on boot", svcName),
					RequiresRoot: true,
					Fix: func(ctx context.Context) error {
						return services.Enable(ctx, svcName)
					},
				},
			})
		}
	} else {
		serviceStatus.State = StateWarning
		serviceStatus.Message = fmt.Sprintf("%s service is not running", c.serviceName)
		svcName := c.serviceName
		fixerID := fmt.Sprintf("start-%s", c.serviceName)
		serviceStatus.Issues = append(serviceStatus.Issues, Issue{
			Severity:  SeverityWarning,
			Message:   fmt.Sprintf("Service %s is not active", c.serviceName),
			Details:   fmt.Sprintf("Start and enable with: sudo systemctl enable --now %s", c.serviceName),
			FixerID:   fixerID,
			FixerDesc: fmt.Sprintf("Start and enable %s service", c.serviceName),
			Fixer: &Fixer{
				Description:  fmt.Sprintf("Start and enable %s service", svcName),
				RequiresRoot: true,
				Fix: func(ctx context.Context) error {
					// If minimal config is set and config file doesn't exist, write it first
					// This is needed for dnsmasq to use bind-dynamic before starting
					if c.minimalConfig != "" && c.configPath != "" {
						if _, err := c.fs.Stat(c.configPath); err != nil {
							// Config doesn't exist, write minimal config
							if err := c.fs.WriteFile(c.configPath, []byte(c.minimalConfig), 0644); err != nil {
								return fmt.Errorf("failed to write minimal config: %w", err)
							}
						}
					}
					// Enable the service on boot
					if err := services.Enable(ctx, svcName); err != nil {
						return fmt.Errorf("failed to enable service: %w", err)
					}
					// Start the service
					return services.Start(ctx, svcName)
				},
			},
		})
	}
	status.SubChecks = append(status.SubChecks, serviceStatus)

	// Aggregate overall status
	hasError := false
	hasWarning := false
	for _, sub := range status.SubChecks {
		if sub.State == StateError {
			hasError = true
			status.Issues = append(status.Issues, sub.Issues...)
		} else if sub.State == StateWarning {
			hasWarning = true
			status.Issues = append(status.Issues, sub.Issues...)
		}
	}

	if hasError {
		status.State = StateError
		status.Message = fmt.Sprintf("%s has errors", c.Name())
	} else if hasWarning {
		status.State = StateWarning
		status.Message = fmt.Sprintf("%s has warnings", c.Name())
	} else {
		status.State = StateOK
		status.Message = fmt.Sprintf("%s is fully operational", c.Name())
	}

	return status
}

func (c *ServiceCheck) getPackageName() string {
	packageMap := map[string]string{
		"hostapd":  "hostapd",
		"dnsmasq":  "dnsmasq",
		"wg":       "wireguard-tools",
		"iptables": "iptables",
		"ip":       "iproute2",
		"iw":       "iw",
		"haproxy":  "haproxy",
	}
	if pkg, ok := packageMap[c.id]; ok {
		return pkg
	}
	return c.id
}

// WiFiInterfaceCheck checks for WiFi interfaces that support AP mode
type WiFiInterfaceCheck struct {
	BaseCheck
}

func NewWiFiInterfaceCheck(runner system.CommandRunner, fs system.FileSystem) *WiFiInterfaceCheck {
	return &WiFiInterfaceCheck{
		BaseCheck: NewBaseCheck("wifi-interfaces", "WiFi AP Capability", "Check for WiFi interfaces supporting AP mode", []string{"iw"}, runner, fs),
	}
}

func (c *WiFiInterfaceCheck) Run(ctx context.Context) *Status {
	status := &Status{
		CheckID:     c.ID(),
		Name:        c.Name(),
		Description: c.Description(),
	}

	// Get WiFi interfaces
	devOut, err := c.runner.Run(ctx, "iw", "dev")
	if err != nil {
		status.State = StateWarning
		status.Message = "Could not enumerate WiFi interfaces"
		return status
	}

	// Parse interfaces and their PHYs
	var interfaces []string
	var currentPhy string
	phyMap := make(map[string]string) // interface -> phy

	for _, line := range strings.Split(string(devOut), "\n") {
		line = strings.TrimSpace(line)
		if strings.HasPrefix(line, "phy#") {
			currentPhy = line
		}
		if strings.HasPrefix(line, "Interface ") {
			iface := strings.TrimPrefix(line, "Interface ")
			interfaces = append(interfaces, iface)
			phyMap[iface] = currentPhy
		}
	}

	if len(interfaces) == 0 {
		status.State = StateWarning
		status.Message = "No WiFi interfaces found"
		status.Issues = append(status.Issues, Issue{
			Severity: SeverityWarning,
			Message:  "No WiFi adapters detected",
			Details:  "Connect a compatible USB WiFi adapter or enable built-in WiFi",
		})
		return status
	}

	// Check each interface for AP capability
	var apCapable []string
	for _, iface := range interfaces {
		phy := phyMap[iface]
		if phy == "" {
			continue
		}

		// Get PHY info
		phyName := "phy" + strings.TrimPrefix(phy, "phy#")
		phyOut, err := c.runner.Run(ctx, "iw", phyName, "info")
		if err != nil {
			continue
		}

		if strings.Contains(string(phyOut), "* AP") {
			apCapable = append(apCapable, iface)
		}
	}

	if len(apCapable) == 0 {
		status.State = StateWarning
		status.Message = fmt.Sprintf("Found %d WiFi interface(s), none support AP mode", len(interfaces))
		status.Issues = append(status.Issues, Issue{
			Severity: SeverityWarning,
			Message:  "No WiFi adapters support Access Point mode",
			Details:  "Your WiFi adapter(s) do not support hosting an access point. Consider using a different adapter.",
		})
		return status
	}

	status.State = StateOK
	status.Message = fmt.Sprintf("%d interface(s) support AP mode: %s", len(apCapable), strings.Join(apCapable, ", "))
	return status
}

// LANGatewayCheck verifies the LAN gateway is configured with a private IP
type LANGatewayCheck struct {
	BaseCheck
	bridgeName   string
	expectedIP   string // Optional: expected IP in CIDR notation (e.g., "192.168.1.1/24")
	wanInterface string // WAN interface to check for conflicts
}

// NewLANGatewayCheck creates a new LAN gateway check
func NewLANGatewayCheck(bridgeName, expectedIP, wanInterface string, runner system.CommandRunner, fs system.FileSystem) *LANGatewayCheck {
	return &LANGatewayCheck{
		BaseCheck:    NewBaseCheck("lan-gateway", "LAN Gateway", "Check LAN bridge has gateway IP configured", []string{"ip"}, runner, fs),
		bridgeName:   bridgeName,
		expectedIP:   expectedIP,
		wanInterface: wanInterface,
	}
}

// getWANIP returns the WAN interface's IP address
func (c *LANGatewayCheck) getWANIP(ctx context.Context) string {
	if c.wanInterface == "" {
		return ""
	}
	out, err := c.runner.Run(ctx, "ip", "-4", "addr", "show", c.wanInterface)
	if err != nil {
		return ""
	}
	for _, line := range strings.Split(string(out), "\n") {
		line = strings.TrimSpace(line)
		if strings.HasPrefix(line, "inet ") {
			parts := strings.Fields(line)
			if len(parts) >= 2 {
				return strings.Split(parts[1], "/")[0]
			}
		}
	}
	return ""
}

func (c *LANGatewayCheck) Run(ctx context.Context) *Status {
	status := &Status{
		CheckID:     c.ID(),
		Name:        c.Name(),
		Description: c.Description(),
	}

	// Check if bridge interface exists
	out, err := c.runner.Run(ctx, "ip", "link", "show", c.bridgeName)
	if err != nil {
		status.State = StateError
		status.Message = fmt.Sprintf("Bridge %s not found", c.bridgeName)
		status.Issues = append(status.Issues, Issue{
			Severity: SeverityCritical,
			Message:  fmt.Sprintf("LAN bridge interface '%s' does not exist", c.bridgeName),
			Details:  "The LAN bridge must be created for router functionality. Run setup to configure.",
		})
		return status
	}

	// Check if bridge is administratively UP (look for UP in flags like <BROADCAST,MULTICAST,UP>)
	// Note: "state DOWN" can appear when bridge has no carrier (no ports), but that's OK
	// We check the flags section, not the state, to see if it's administratively up
	isAdminUp := strings.Contains(string(out), ",UP>") || strings.Contains(string(out), ",UP,")
	if !isAdminUp {
		status.State = StateWarning
		status.Message = fmt.Sprintf("Bridge %s exists but is not UP", c.bridgeName)
		bridgeName := c.bridgeName
		status.Issues = append(status.Issues, Issue{
			Severity:  SeverityWarning,
			Message:   fmt.Sprintf("Bridge %s is not administratively up", c.bridgeName),
			Details:   fmt.Sprintf("Bring up with: sudo ip link set %s up", c.bridgeName),
			FixerID:   "bring-up-bridge",
			FixerDesc: fmt.Sprintf("Bring up %s interface", c.bridgeName),
			Fixer: &Fixer{
				Description:  fmt.Sprintf("Bring up bridge %s", bridgeName),
				RequiresRoot: true,
				Fix: func(ctx context.Context) error {
					_, err := c.runner.Run(ctx, "ip", "link", "set", bridgeName, "up")
					return err
				},
			},
		})
	}

	// Get IP addresses on the bridge
	addrOut, err := c.runner.Run(ctx, "ip", "-4", "addr", "show", c.bridgeName)
	if err != nil {
		status.State = StateError
		status.Message = "Failed to get bridge IP addresses"
		return status
	}

	// Parse IP addresses from output
	var foundIPs []string
	for _, line := range strings.Split(string(addrOut), "\n") {
		line = strings.TrimSpace(line)
		if strings.HasPrefix(line, "inet ") {
			parts := strings.Fields(line)
			if len(parts) >= 2 {
				foundIPs = append(foundIPs, parts[1])
			}
		}
	}

	if len(foundIPs) == 0 {
		status.State = StateError
		status.Message = fmt.Sprintf("Bridge %s has no IPv4 address", c.bridgeName)
		issue := Issue{
			Severity: SeverityCritical,
			Message:  fmt.Sprintf("No IPv4 address configured on %s", c.bridgeName),
			Details:  "The LAN bridge needs a gateway IP address for clients to connect. Configure via DHCP settings page.",
		}
		// Only offer fixer if we can verify no WAN conflict
		if c.expectedIP != "" {
			wanIP := c.getWANIP(ctx)
			if wanIP == "" {
				// Can't detect WAN - don't offer potentially dangerous fixer
				issue.Details = "The LAN bridge needs a gateway IP. Configure WAN interface first, then use DHCP settings page to set a non-conflicting LAN subnet."
			} else if network.SubnetsConflict(wanIP, c.expectedIP) {
				// Conflict detected - don't offer fixer
				issue.Details = fmt.Sprintf("Configured LAN IP %s conflicts with WAN subnet (%s). Update LAN address in DHCP settings to use a different subnet.", c.expectedIP, wanIP)
			} else {
				// Safe to offer fixer - WAN detected and no conflict
				bridgeName := c.bridgeName
				expectedIP := c.expectedIP
				runner := c.runner
				issue.FixerID = "add-bridge-ip"
				issue.FixerDesc = fmt.Sprintf("Add %s to %s", expectedIP, bridgeName)
				issue.Fixer = &Fixer{
					Description:  fmt.Sprintf("Configure %s with IP %s", bridgeName, expectedIP),
					RequiresRoot: true,
					Fix: func(ctx context.Context) error {
						_, err := runner.Run(ctx, "ip", "addr", "add", expectedIP, "dev", bridgeName)
						if err != nil {
							return fmt.Errorf("failed to add IP: %w", err)
						}
						runner.Run(ctx, "ip", "link", "set", bridgeName, "up")
						return nil
					},
				}
			}
		}
		status.Issues = append(status.Issues, issue)
		return status
	}

	// Check if we have a private IP (RFC1918)
	hasPrivateIP := false
	for _, ip := range foundIPs {
		ipOnly := strings.Split(ip, "/")[0]
		if isPrivateIP(ipOnly) {
			hasPrivateIP = true
			break
		}
	}

	if !hasPrivateIP {
		status.State = StateWarning
		status.Message = fmt.Sprintf("Bridge %s has no private IP", c.bridgeName)
		status.Issues = append(status.Issues, Issue{
			Severity: SeverityWarning,
			Message:  "No RFC1918 private IP address found on LAN bridge",
			Details:  fmt.Sprintf("Found IPs: %s. A private IP (10.x, 172.16-31.x, 192.168.x) is recommended for LAN", strings.Join(foundIPs, ", ")),
		})
		return status
	}

	// If expected IP is set, verify it matches
	if c.expectedIP != "" {
		found := false
		for _, ip := range foundIPs {
			if ip == c.expectedIP {
				found = true
				break
			}
		}
		if !found {
			status.State = StateWarning
			status.Message = fmt.Sprintf("Expected IP %s not found on %s", c.expectedIP, c.bridgeName)
			// Capture variables for closure
			bridgeName := c.bridgeName
			expectedIP := c.expectedIP
			runner := c.runner
			status.Issues = append(status.Issues, Issue{
				Severity:  SeverityWarning,
				Message:   fmt.Sprintf("Expected gateway IP %s not configured", c.expectedIP),
				Details:   fmt.Sprintf("Found: %s. Click fix to apply expected IP or update config to match current IP.", strings.Join(foundIPs, ", ")),
				FixerID:   "configure-gateway-ip",
				FixerDesc: fmt.Sprintf("Configure %s with %s", c.bridgeName, c.expectedIP),
				Fixer: &Fixer{
					Description:  fmt.Sprintf("Add IP %s to %s", expectedIP, bridgeName),
					RequiresRoot: true,
					Fix: func(ctx context.Context) error {
						// Add expected IP without removing existing IPs (non-destructive)
						// This preserves network connectivity while adding the configured IP
						_, err := runner.Run(ctx, "ip", "addr", "add", expectedIP, "dev", bridgeName)
						if err != nil {
							// IP might already exist, which is fine
							if !strings.Contains(err.Error(), "RTNETLINK answers: File exists") {
								return fmt.Errorf("failed to add IP: %w", err)
							}
						}
						runner.Run(ctx, "ip", "link", "set", bridgeName, "up")
						return nil
					},
				},
			})
			return status
		}
	}

	status.State = StateOK
	status.Message = fmt.Sprintf("LAN gateway configured: %s on %s", strings.Join(foundIPs, ", "), c.bridgeName)
	return status
}

// isPrivateIP checks if an IP is in RFC1918 private ranges
func isPrivateIP(ip string) bool {
	// 10.0.0.0/8, 172.16.0.0/12, 192.168.0.0/16
	if strings.HasPrefix(ip, "10.") {
		return true
	}
	if strings.HasPrefix(ip, "192.168.") {
		return true
	}
	if strings.HasPrefix(ip, "172.") {
		parts := strings.Split(ip, ".")
		if len(parts) >= 2 {
			var second int
			fmt.Sscanf(parts[1], "%d", &second)
			if second >= 16 && second <= 31 {
				return true
			}
		}
	}
	return false
}

// NATCheck verifies NAT/masquerade is configured for routing
type NATCheck struct {
	BaseCheck
	wanInterface     string
	wanMode          string   // dhcp, static, pppoe, wifi
	wifiAPInterfaces []string // WiFi interfaces used as access points (LAN, not WAN)
}

// NewNATCheck creates a new NAT check
func NewNATCheck(wanInterface, wanMode string, wifiAPInterfaces []string, runner system.CommandRunner, fs system.FileSystem) *NATCheck {
	return &NATCheck{
		BaseCheck:        NewBaseCheck("nat", "NAT/Masquerade", "Check NAT masquerade is configured for WAN", []string{"iptables"}, runner, fs),
		wanInterface:     wanInterface,
		wanMode:          wanMode,
		wifiAPInterfaces: wifiAPInterfaces,
	}
}

func (c *NATCheck) Run(ctx context.Context) *Status {
	status := &Status{
		CheckID:     c.ID(),
		Name:        c.Name(),
		Description: c.Description(),
	}

	// Check iptables NAT table POSTROUTING chain for MASQUERADE rules
	out, err := c.runner.Run(ctx, "iptables", "-t", "nat", "-L", "POSTROUTING", "-n", "-v")
	if err != nil {
		status.State = StateError
		status.Message = "Failed to query iptables NAT rules"
		status.Issues = append(status.Issues, Issue{
			Severity: SeverityCritical,
			Message:  "Cannot read iptables NAT table",
			Details:  fmt.Sprintf("Error: %v. Ensure iptables is installed and you have root privileges.", err),
		})
		return status
	}

	// Look for MASQUERADE rule
	hasMasquerade := false
	hasWANMasquerade := false
	lines := strings.Split(string(out), "\n")

	for _, line := range lines {
		if strings.Contains(line, "MASQUERADE") {
			hasMasquerade = true
			// Check if it's for our WAN interface
			if c.wanInterface != "" && strings.Contains(line, c.wanInterface) {
				hasWANMasquerade = true
			}
		}
	}

	if !hasMasquerade {
		status.State = StateError
		status.Message = "No NAT masquerade rules configured"

		fixCmd := "iptables -t nat -A POSTROUTING -o " + c.wanInterface + " -j MASQUERADE"
		if c.wanInterface == "" {
			fixCmd = "iptables -t nat -A POSTROUTING -o <WAN_INTERFACE> -j MASQUERADE"
		}

		status.Issues = append(status.Issues, Issue{
			Severity:  SeverityCritical,
			Message:   "NAT masquerade not configured",
			Details:   fmt.Sprintf("LAN clients cannot access internet without NAT. Add with: sudo %s", fixCmd),
			FixerID:   "setup-nat",
			FixerDesc: "Configure NAT masquerade",
			Fixer: &Fixer{
				Description:  "Add NAT masquerade rule for WAN interface",
				RequiresRoot: true,
				Fix: func(ctx context.Context) error {
					if c.wanInterface == "" {
						return fmt.Errorf("WAN interface not specified")
					}
					_, err := c.runner.Run(ctx, "iptables", "-t", "nat", "-A", "POSTROUTING", "-o", c.wanInterface, "-j", "MASQUERADE")
					return err
				},
			},
		})
		return status
	}

	if c.wanInterface != "" && !hasWANMasquerade {
		// Check if the WAN interface is actually configured as a WiFi AP (LAN, not WAN)
		// In this case, NAT is expected on a different interface, so don't warn
		isWiFiAP := false
		for _, apIface := range c.wifiAPInterfaces {
			if apIface == c.wanInterface {
				isWiFiAP = true
				break
			}
		}

		if isWiFiAP {
			// WiFi AP interfaces are LAN interfaces, not WAN - NAT is on the actual WAN
			status.State = StateOK
			status.Message = fmt.Sprintf("NAT masquerade is configured (interface %s is WiFi AP)", c.wanInterface)
			return status
		}

		// If WAN mode is WiFi and NAT exists (on another interface), that's OK
		// WiFi WAN might be secondary/backup, with primary WAN having NAT configured
		if c.wanMode == "wifi" && hasMasquerade {
			status.State = StateOK
			status.Message = "NAT masquerade is configured (WiFi WAN uses existing NAT)"
			return status
		}

		status.State = StateWarning
		status.Message = fmt.Sprintf("NAT exists but not for WAN interface %s", c.wanInterface)
		status.Issues = append(status.Issues, Issue{
			Severity: SeverityWarning,
			Message:  fmt.Sprintf("Masquerade rule not found for interface %s", c.wanInterface),
			Details:  "NAT may be configured for a different interface",
		})
		return status
	}

	if c.wanInterface != "" {
		status.State = StateOK
		status.Message = fmt.Sprintf("NAT masquerade active on %s", c.wanInterface)
	} else {
		status.State = StateOK
		status.Message = "NAT masquerade is configured"
	}
	return status
}

// DHCPRangeCheck verifies DHCP is configured with a valid range
type DHCPRangeCheck struct {
	BaseCheck
	dhcpStart    string
	dhcpEnd      string
	lanSubnet    string // e.g., "192.168.1.0/24"
	wanInterface string
	lanBridge    string
}

// NewDHCPRangeCheck creates a new DHCP range check
func NewDHCPRangeCheck(dhcpStart, dhcpEnd, lanSubnet, wanInterface, lanBridge string, runner system.CommandRunner, fs system.FileSystem) *DHCPRangeCheck {
	return &DHCPRangeCheck{
		BaseCheck:    NewBaseCheck("dhcp-range", "DHCP Range", "Check DHCP range is configured for LAN clients", []string{"dnsmasq"}, runner, fs),
		dhcpStart:    dhcpStart,
		dhcpEnd:      dhcpEnd,
		lanSubnet:    lanSubnet,
		wanInterface: wanInterface,
		lanBridge:    lanBridge,
	}
}

func (c *DHCPRangeCheck) Run(ctx context.Context) *Status {
	status := &Status{
		CheckID:     c.ID(),
		Name:        c.Name(),
		Description: c.Description(),
	}

	// Read dnsmasq DHCP config to check for dhcp-range
	configPath := "/etc/dnsmasq.d/ubuntu-router-dhcp.conf"
	data, err := c.fs.ReadFile(configPath)
	if err != nil {
		status.State = StateWarning
		status.Message = "DHCP config not found"

		// Calculate suggested LAN subnet based on WAN
		suggestedGateway, suggestedStart, suggestedEnd := c.calculateLANSubnet(ctx)

		status.Issues = append(status.Issues, Issue{
			Severity:  SeverityWarning,
			Message:   "DHCP config not found at " + configPath,
			Details:   fmt.Sprintf("Will create default config with gateway %s, range %s-%s", suggestedGateway, suggestedStart, suggestedEnd),
			FixerID:   "create-dhcp-config",
			FixerDesc: "Create default DHCP configuration",
			Fixer: &Fixer{
				Description:  "Create DHCP config with auto-detected subnet",
				RequiresRoot: true,
				Fix: func(ctx context.Context) error {
					return c.createDefaultDHCPConfig(ctx, suggestedGateway, suggestedStart, suggestedEnd)
				},
			},
		})
		return status
	}

	// Look for dhcp-range directive
	content := string(data)
	if !strings.Contains(content, "dhcp-range=") {
		status.State = StateWarning
		status.Message = "No DHCP range configured"

		suggestedGateway, suggestedStart, suggestedEnd := c.calculateLANSubnet(ctx)

		status.Issues = append(status.Issues, Issue{
			Severity:  SeverityWarning,
			Message:   "No dhcp-range directive found in dnsmasq config",
			Details:   fmt.Sprintf("Will configure with gateway %s, range %s-%s", suggestedGateway, suggestedStart, suggestedEnd),
			FixerID:   "create-dhcp-config",
			FixerDesc: "Create default DHCP configuration",
			Fixer: &Fixer{
				Description:  "Create DHCP config with auto-detected subnet",
				RequiresRoot: true,
				Fix: func(ctx context.Context) error {
					return c.createDefaultDHCPConfig(ctx, suggestedGateway, suggestedStart, suggestedEnd)
				},
			},
		})
		return status
	}

	// Extract the dhcp-range line for reporting
	var dhcpRange string
	for _, line := range strings.Split(content, "\n") {
		if strings.HasPrefix(line, "dhcp-range=") {
			dhcpRange = strings.TrimPrefix(line, "dhcp-range=")
			break
		}
	}

	// Verify expected range if provided
	if c.dhcpStart != "" && c.dhcpEnd != "" {
		expectedRange := c.dhcpStart + "," + c.dhcpEnd
		if !strings.Contains(dhcpRange, c.dhcpStart) || !strings.Contains(dhcpRange, c.dhcpEnd) {
			status.State = StateWarning
			status.Message = "DHCP range doesn't match expected"
			status.Issues = append(status.Issues, Issue{
				Severity: SeverityInfo,
				Message:  fmt.Sprintf("Expected range %s, found %s", expectedRange, dhcpRange),
				Details:  "DHCP range may have been customized",
			})
			return status
		}
	}

	status.State = StateOK
	status.Message = fmt.Sprintf("DHCP range configured: %s", dhcpRange)
	return status
}

// calculateLANSubnet determines an appropriate LAN subnet based on WAN IP
// Returns gateway, dhcp_start, dhcp_end
func (c *DHCPRangeCheck) calculateLANSubnet(ctx context.Context) (string, string, string) {
	if c.wanInterface == "" {
		return network.CalculateLANSubnet("")
	}

	// Get WAN IP
	out, err := c.runner.Run(ctx, "ip", "-4", "addr", "show", c.wanInterface)
	if err != nil {
		return network.CalculateLANSubnet("")
	}

	// Parse IP from output (look for "inet x.x.x.x/xx")
	var wanIP string
	for _, line := range strings.Split(string(out), "\n") {
		line = strings.TrimSpace(line)
		if strings.HasPrefix(line, "inet ") {
			parts := strings.Fields(line)
			if len(parts) >= 2 {
				wanIP = strings.Split(parts[1], "/")[0]
				break
			}
		}
	}

	return network.CalculateLANSubnet(wanIP)
}

// createDefaultDHCPConfig writes a default DHCP configuration file
func (c *DHCPRangeCheck) createDefaultDHCPConfig(ctx context.Context, gateway, dhcpStart, dhcpEnd string) error {
	configPath := "/etc/dnsmasq.d/ubuntu-router-dhcp.conf"

	var sb strings.Builder
	sb.WriteString("# Ubuntu Router DHCP configuration\n")
	sb.WriteString("# Auto-generated default configuration\n\n")

	sb.WriteString("# DHCP settings\n")
	sb.WriteString(fmt.Sprintf("dhcp-range=%s,%s,24h\n", dhcpStart, dhcpEnd))
	sb.WriteString(fmt.Sprintf("dhcp-option=option:router,%s\n", gateway))
	sb.WriteString(fmt.Sprintf("dhcp-option=option:dns-server,%s\n", gateway))
	sb.WriteString("dhcp-option=option:domain-name,lan\n")
	sb.WriteString("\n")

	if err := c.fs.WriteFile(configPath, []byte(sb.String()), 0644); err != nil {
		return fmt.Errorf("failed to write DHCP config: %w", err)
	}

	// Also need to configure the LAN bridge with the gateway IP
	if c.lanBridge != "" {
		// Add IP to bridge
		_, err := c.runner.Run(ctx, "ip", "addr", "add", gateway+"/24", "dev", c.lanBridge)
		if err != nil {
			// Might already exist, try to continue
		}
		// Bring up the bridge
		c.runner.Run(ctx, "ip", "link", "set", c.lanBridge, "up")
	}

	// Restart dnsmasq to pick up the new config
	c.runner.Run(ctx, "systemctl", "restart", "dnsmasq")

	return nil
}

// WireGuardInterfaceCheck checks if a WireGuard interface is up and running
type WireGuardInterfaceCheck struct {
	BaseCheck
	interfaceName string
	configPath    string
	enabled       bool
}

// NewWireGuardInterfaceCheck creates a new WireGuard interface check
func NewWireGuardInterfaceCheck(interfaceName, configPath string, enabled bool, runner system.CommandRunner, fs system.FileSystem) *WireGuardInterfaceCheck {
	return &WireGuardInterfaceCheck{
		BaseCheck:     NewBaseCheck("wireguard-"+interfaceName, "WireGuard "+interfaceName, fmt.Sprintf("Check WireGuard interface %s status", interfaceName), []string{"wg", "wireguard-module"}, runner, fs),
		interfaceName: interfaceName,
		configPath:    configPath,
		enabled:       enabled,
	}
}

func (c *WireGuardInterfaceCheck) Run(ctx context.Context) *Status {
	status := &Status{
		CheckID:     c.ID(),
		Name:        c.Name(),
		Description: c.Description(),
	}

	// If not enabled, just report that
	if !c.enabled {
		status.State = StateOK
		status.Message = fmt.Sprintf("WireGuard interface %s is disabled", c.interfaceName)
		return status
	}

	// Check if interface exists
	out, err := c.runner.Run(ctx, "ip", "link", "show", c.interfaceName)
	if err != nil {
		status.State = StateWarning
		status.Message = fmt.Sprintf("WireGuard interface %s not found", c.interfaceName)

		// Check if config file exists
		_, configErr := c.fs.Stat(c.configPath)
		if configErr != nil {
			status.Issues = append(status.Issues, Issue{
				Severity: SeverityWarning,
				Message:  fmt.Sprintf("WireGuard interface %s not active and config not found", c.interfaceName),
				Details:  fmt.Sprintf("Expected config at %s. The tunnel may need to be configured.", c.configPath),
			})
		} else {
			// Config exists, offer to start
			interfaceName := c.interfaceName
			status.Issues = append(status.Issues, Issue{
				Severity:  SeverityWarning,
				Message:   fmt.Sprintf("WireGuard interface %s is configured but not running", c.interfaceName),
				Details:   fmt.Sprintf("Config exists at %s. Start with: wg-quick up %s", c.configPath, c.interfaceName),
				FixerID:   fmt.Sprintf("start-wireguard-%s", c.interfaceName),
				FixerDesc: fmt.Sprintf("Start WireGuard %s", c.interfaceName),
				Fixer: &Fixer{
					Description:  fmt.Sprintf("Start WireGuard interface %s (enable auto-start)", interfaceName),
					RequiresRoot: true,
					Fix: func(ctx context.Context) error {
						// Enable systemd auto-start for this interface
						serviceName := fmt.Sprintf("wg-quick@%s", interfaceName)
						c.runner.Run(ctx, "systemctl", "enable", serviceName)
						// Start the interface
						_, err := c.runner.Run(ctx, "wg-quick", "up", interfaceName)
						return err
					},
				},
			})
		}
		return status
	}

	// Interface exists - check if it's UP
	if !strings.Contains(string(out), "state UNKNOWN") && !strings.Contains(string(out), "state UP") {
		status.State = StateWarning
		status.Message = fmt.Sprintf("WireGuard interface %s exists but is not UP", c.interfaceName)
		interfaceName := c.interfaceName
		status.Issues = append(status.Issues, Issue{
			Severity:  SeverityWarning,
			Message:   fmt.Sprintf("Interface %s is not in UP state", c.interfaceName),
			Details:   fmt.Sprintf("Bring up with: ip link set %s up", c.interfaceName),
			FixerID:   fmt.Sprintf("bring-up-wireguard-%s", c.interfaceName),
			FixerDesc: fmt.Sprintf("Bring up %s", c.interfaceName),
			Fixer: &Fixer{
				Description:  fmt.Sprintf("Bring up WireGuard interface %s", interfaceName),
				RequiresRoot: true,
				Fix: func(ctx context.Context) error {
					_, err := c.runner.Run(ctx, "ip", "link", "set", interfaceName, "up")
					return err
				},
			},
		})
		return status
	}

	// Check if we have peers configured using wg show
	wgOut, err := c.runner.Run(ctx, "wg", "show", c.interfaceName)
	if err != nil {
		status.State = StateWarning
		status.Message = fmt.Sprintf("WireGuard %s up but wg show failed", c.interfaceName)
		return status
	}

	// Check for peer connections
	hasPeers := strings.Contains(string(wgOut), "peer:")
	if !hasPeers {
		status.State = StateWarning
		status.Message = fmt.Sprintf("WireGuard %s running but no peers configured", c.interfaceName)
		status.Issues = append(status.Issues, Issue{
			Severity: SeverityInfo,
			Message:  "No peers configured on this interface",
			Details:  "Add peers to establish VPN connections",
		})
		return status
	}

	// Check for recent handshake (connection alive)
	hasHandshake := strings.Contains(string(wgOut), "latest handshake:")
	if hasHandshake {
		status.State = StateOK
		status.Message = fmt.Sprintf("WireGuard %s active with connected peers", c.interfaceName)
	} else {
		status.State = StateOK
		status.Message = fmt.Sprintf("WireGuard %s running, peers configured (awaiting handshake)", c.interfaceName)
	}

	return status
}

// SystemdResolvedCheck checks for potential conflicts with systemd-resolved
type SystemdResolvedCheck struct {
	BaseCheck
}

// NewSystemdResolvedCheck creates a new systemd-resolved check
func NewSystemdResolvedCheck(runner system.CommandRunner, fs system.FileSystem) *SystemdResolvedCheck {
	return &SystemdResolvedCheck{
		BaseCheck: NewBaseCheck("systemd-resolved", "systemd-resolved", "Check for DNS port conflicts with systemd-resolved", []string{"dnsmasq"}, runner, fs),
	}
}

func (c *SystemdResolvedCheck) Run(ctx context.Context) *Status {
	status := &Status{
		CheckID:     c.ID(),
		Name:        c.Name(),
		Description: c.Description(),
	}

	services := system.NewServiceManager(c.runner)

	// Check if systemd-resolved is running
	if !services.IsActive(ctx, "systemd-resolved") {
		status.State = StateOK
		status.Message = "systemd-resolved is not running (no conflict)"
		return status
	}

	// systemd-resolved is running - check if it's using stub listener on 127.0.0.53
	// This is the default and doesn't conflict with dnsmasq on other interfaces
	resolvConf, err := c.fs.ReadFile("/etc/resolv.conf")
	if err != nil {
		status.State = StateWarning
		status.Message = "Could not read /etc/resolv.conf"
		return status
	}

	content := string(resolvConf)

	// Check if using systemd-resolved stub (127.0.0.53) - this is OK with bind-dynamic
	if strings.Contains(content, "127.0.0.53") {
		status.State = StateOK
		status.Message = "systemd-resolved using stub resolver (127.0.0.53) - compatible with dnsmasq bind-dynamic"
		return status
	}

	// Check if pointing to localhost (127.0.0.1) which could conflict
	if strings.Contains(content, "nameserver 127.0.0.1") {
		status.State = StateWarning
		status.Message = "resolv.conf points to 127.0.0.1 - potential DNS conflict"
		status.Issues = append(status.Issues, Issue{
			Severity: SeverityWarning,
			Message:  "DNS resolver configured to use 127.0.0.1",
			Details:  "This may conflict with dnsmasq. Consider using 127.0.0.53 (systemd-resolved stub) or disabling systemd-resolved",
		})
		return status
	}

	status.State = StateOK
	status.Message = "systemd-resolved running - dnsmasq uses bind-dynamic for compatibility"
	return status
}
