/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WireguardP2pRouteImport } from './routes/wireguard-p2p'
import { Route as WireguardRouteImport } from './routes/wireguard'
import { Route as WifiRouteImport } from './routes/wifi'
import { Route as WanRouteImport } from './routes/wan'
import { Route as StatsRouteImport } from './routes/stats'
import { Route as SetupRouteImport } from './routes/setup'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as ServicesRouteImport } from './routes/services'
import { Route as QosRouteImport } from './routes/qos'
import { Route as LoginRouteImport } from './routes/login'
import { Route as InterfacesRouteImport } from './routes/interfaces'
import { Route as FirewallRouteImport } from './routes/firewall'
import { Route as ExternalDnsRouteImport } from './routes/external-dns'
import { Route as DnsRouteImport } from './routes/dns'
import { Route as DhcpRouteImport } from './routes/dhcp'
import { Route as IndexRouteImport } from './routes/index'

const WireguardP2pRoute = WireguardP2pRouteImport.update({
  id: '/wireguard-p2p',
  path: '/wireguard-p2p',
  getParentRoute: () => rootRouteImport,
} as any)
const WireguardRoute = WireguardRouteImport.update({
  id: '/wireguard',
  path: '/wireguard',
  getParentRoute: () => rootRouteImport,
} as any)
const WifiRoute = WifiRouteImport.update({
  id: '/wifi',
  path: '/wifi',
  getParentRoute: () => rootRouteImport,
} as any)
const WanRoute = WanRouteImport.update({
  id: '/wan',
  path: '/wan',
  getParentRoute: () => rootRouteImport,
} as any)
const StatsRoute = StatsRouteImport.update({
  id: '/stats',
  path: '/stats',
  getParentRoute: () => rootRouteImport,
} as any)
const SetupRoute = SetupRouteImport.update({
  id: '/setup',
  path: '/setup',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesRoute = ServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)
const QosRoute = QosRouteImport.update({
  id: '/qos',
  path: '/qos',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const InterfacesRoute = InterfacesRouteImport.update({
  id: '/interfaces',
  path: '/interfaces',
  getParentRoute: () => rootRouteImport,
} as any)
const FirewallRoute = FirewallRouteImport.update({
  id: '/firewall',
  path: '/firewall',
  getParentRoute: () => rootRouteImport,
} as any)
const ExternalDnsRoute = ExternalDnsRouteImport.update({
  id: '/external-dns',
  path: '/external-dns',
  getParentRoute: () => rootRouteImport,
} as any)
const DnsRoute = DnsRouteImport.update({
  id: '/dns',
  path: '/dns',
  getParentRoute: () => rootRouteImport,
} as any)
const DhcpRoute = DhcpRouteImport.update({
  id: '/dhcp',
  path: '/dhcp',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dhcp': typeof DhcpRoute
  '/dns': typeof DnsRoute
  '/external-dns': typeof ExternalDnsRoute
  '/firewall': typeof FirewallRoute
  '/interfaces': typeof InterfacesRoute
  '/login': typeof LoginRoute
  '/qos': typeof QosRoute
  '/services': typeof ServicesRoute
  '/settings': typeof SettingsRoute
  '/setup': typeof SetupRoute
  '/stats': typeof StatsRoute
  '/wan': typeof WanRoute
  '/wifi': typeof WifiRoute
  '/wireguard': typeof WireguardRoute
  '/wireguard-p2p': typeof WireguardP2pRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dhcp': typeof DhcpRoute
  '/dns': typeof DnsRoute
  '/external-dns': typeof ExternalDnsRoute
  '/firewall': typeof FirewallRoute
  '/interfaces': typeof InterfacesRoute
  '/login': typeof LoginRoute
  '/qos': typeof QosRoute
  '/services': typeof ServicesRoute
  '/settings': typeof SettingsRoute
  '/setup': typeof SetupRoute
  '/stats': typeof StatsRoute
  '/wan': typeof WanRoute
  '/wifi': typeof WifiRoute
  '/wireguard': typeof WireguardRoute
  '/wireguard-p2p': typeof WireguardP2pRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dhcp': typeof DhcpRoute
  '/dns': typeof DnsRoute
  '/external-dns': typeof ExternalDnsRoute
  '/firewall': typeof FirewallRoute
  '/interfaces': typeof InterfacesRoute
  '/login': typeof LoginRoute
  '/qos': typeof QosRoute
  '/services': typeof ServicesRoute
  '/settings': typeof SettingsRoute
  '/setup': typeof SetupRoute
  '/stats': typeof StatsRoute
  '/wan': typeof WanRoute
  '/wifi': typeof WifiRoute
  '/wireguard': typeof WireguardRoute
  '/wireguard-p2p': typeof WireguardP2pRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dhcp'
    | '/dns'
    | '/external-dns'
    | '/firewall'
    | '/interfaces'
    | '/login'
    | '/qos'
    | '/services'
    | '/settings'
    | '/setup'
    | '/stats'
    | '/wan'
    | '/wifi'
    | '/wireguard'
    | '/wireguard-p2p'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dhcp'
    | '/dns'
    | '/external-dns'
    | '/firewall'
    | '/interfaces'
    | '/login'
    | '/qos'
    | '/services'
    | '/settings'
    | '/setup'
    | '/stats'
    | '/wan'
    | '/wifi'
    | '/wireguard'
    | '/wireguard-p2p'
  id:
    | '__root__'
    | '/'
    | '/dhcp'
    | '/dns'
    | '/external-dns'
    | '/firewall'
    | '/interfaces'
    | '/login'
    | '/qos'
    | '/services'
    | '/settings'
    | '/setup'
    | '/stats'
    | '/wan'
    | '/wifi'
    | '/wireguard'
    | '/wireguard-p2p'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DhcpRoute: typeof DhcpRoute
  DnsRoute: typeof DnsRoute
  ExternalDnsRoute: typeof ExternalDnsRoute
  FirewallRoute: typeof FirewallRoute
  InterfacesRoute: typeof InterfacesRoute
  LoginRoute: typeof LoginRoute
  QosRoute: typeof QosRoute
  ServicesRoute: typeof ServicesRoute
  SettingsRoute: typeof SettingsRoute
  SetupRoute: typeof SetupRoute
  StatsRoute: typeof StatsRoute
  WanRoute: typeof WanRoute
  WifiRoute: typeof WifiRoute
  WireguardRoute: typeof WireguardRoute
  WireguardP2pRoute: typeof WireguardP2pRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/wireguard-p2p': {
      id: '/wireguard-p2p'
      path: '/wireguard-p2p'
      fullPath: '/wireguard-p2p'
      preLoaderRoute: typeof WireguardP2pRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/wireguard': {
      id: '/wireguard'
      path: '/wireguard'
      fullPath: '/wireguard'
      preLoaderRoute: typeof WireguardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/wifi': {
      id: '/wifi'
      path: '/wifi'
      fullPath: '/wifi'
      preLoaderRoute: typeof WifiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/wan': {
      id: '/wan'
      path: '/wan'
      fullPath: '/wan'
      preLoaderRoute: typeof WanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stats': {
      id: '/stats'
      path: '/stats'
      fullPath: '/stats'
      preLoaderRoute: typeof StatsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/setup': {
      id: '/setup'
      path: '/setup'
      fullPath: '/setup'
      preLoaderRoute: typeof SetupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/qos': {
      id: '/qos'
      path: '/qos'
      fullPath: '/qos'
      preLoaderRoute: typeof QosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/interfaces': {
      id: '/interfaces'
      path: '/interfaces'
      fullPath: '/interfaces'
      preLoaderRoute: typeof InterfacesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/firewall': {
      id: '/firewall'
      path: '/firewall'
      fullPath: '/firewall'
      preLoaderRoute: typeof FirewallRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/external-dns': {
      id: '/external-dns'
      path: '/external-dns'
      fullPath: '/external-dns'
      preLoaderRoute: typeof ExternalDnsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dns': {
      id: '/dns'
      path: '/dns'
      fullPath: '/dns'
      preLoaderRoute: typeof DnsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dhcp': {
      id: '/dhcp'
      path: '/dhcp'
      fullPath: '/dhcp'
      preLoaderRoute: typeof DhcpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DhcpRoute: DhcpRoute,
  DnsRoute: DnsRoute,
  ExternalDnsRoute: ExternalDnsRoute,
  FirewallRoute: FirewallRoute,
  InterfacesRoute: InterfacesRoute,
  LoginRoute: LoginRoute,
  QosRoute: QosRoute,
  ServicesRoute: ServicesRoute,
  SettingsRoute: SettingsRoute,
  SetupRoute: SetupRoute,
  StatsRoute: StatsRoute,
  WanRoute: WanRoute,
  WifiRoute: WifiRoute,
  WireguardRoute: WireguardRoute,
  WireguardP2pRoute: WireguardP2pRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
